### ISSUE TITLE
Make torch and some other dependencies optional

### ISSUE THREAD

**Issue by meakbiyik** [facebookresearch/Kats#101]
Hi, kudos to your work as this package will be quite useful. However, it was quite a bad surprise for me to add this package to my project dependencies and see huge and non-environment-friendly packages such as pytorch, gpytorch, llvmlite and even plotly being installed into my environment. I only plan to use some changepoint detection methods and maybe visualizations, and I highly doubt that (though, of course correct me if I am wrong) the whole torch stack is necessary for such a task. Similarly, I imagine plotly can easily be made an optional dependency as well, since matplotlib is still the de facto plotting library of python and it would not be in the interest of majority of the users to install a data analysis package and get a big python-js bundle with it.

**Comment by michaelbrundage** [comment]
Thanks for reporting this. I've fixed this in f6d9d94905d3e1ea9c70c6c01f9828fde97cab71. `pip` doesn't have a way for us to keep `pip install kats` the default and allow users to optionally opt-out of some functionality; only the opposite. So, to get a reduced version of Kats without Pytorch, plotly, and many other packages (everything listed in [`test_requirements.txt`](https://github.com/facebookresearch/Kats/blob/master/test_requirements.txt)), you can now use

```
MINIMAL=1 pip install .
```

from the root level of the Kats source, and in the future (after we release the next version of Kats),

```
MINIMAL=1 pip install kats
```

If you later decide you want some of those additional functionalities, you can manually install the ones you want, or install all of them with

```
pip install -r test_requirements.txt
``

**Comment by meakbiyik** [comment]
@michaelbrundage thanks for the quick resolve. One question though: why not [poetry](https://python-poetry.org/)? I thought it was becoming kind of an industry standard by now, and you can add both the `optional` tag to packages, and also bundle them with `extras` flexibly. Also since it is PEP 517 compliant, the whole previous pipeline with `pip` will continue to work. 

[An example](https://github.com/meakbiyik/soccerbars/blob/master/pyproject.toml) from a package I have written: the CLI component is optional, so those packages are marked as `optional` and can be installed by specifying the cli extra during install (or after install): `pip install [blah] -E cli` .

**Comment by michaelbrundage** [comment]
@meakbiyik The goal was to remove dependencies, not add a new one. However, PRs always welcome. Kats would need a `pyproject.toml` first, and need to install smoothly across all platforms we support.

**Comment by michaelbrundage** [comment]
Thanks for the PR. Is there any reason to add a second variable, or should we just rename the one variable from `MINIMAL` to `MINIMAL_KATS` to avoid potential conflicts with any other projects?

Can you point to any examples of other projects that use the `MINIMAL` variable?
