### ISSUE TITLE
Timeseries sampled every second (and sub-second)?

### ISSUE THREAD

**Issue by snazzybloke** [facebookresearch/Kats#102]
My data (Earth's electromagnetic field components) is typically sampled with a rate 1-100 Hz, with a daily periodicity (following the solar cycle). For the "long period" (1 Hz, i.e. one sample per second) the script detectors/outlier.py makes an error and incorrectly infers that the period is "S" (i.e., a second) and passes "S" to the tsatools module, which can handle only hourly ("H") to annual ("A") periods. Hence, the execution crashes. On the other hand, if I change the line 88 from:
result = seasonal_decompose(original, model=self.decomp)
to 
result = seasonal_decompose(original, model=self.decomp, freq=86400)
it runs fine.
Would it be possible to make a provision for the user to supply their own freq value?

**Comment by snazzybloke** [comment]
Just spotted: the issue is almost identical to 98.
In my case though the error reads:

!! ValueError: freq S not understood. Please report if you think this is in error.
ERROR:root:Outlier Detection Failed

**Comment by michaelbrundage** [comment]
Yes, this is related to #98 Kats doesn't currently support this well, but we're discussing changes to improve support for user-supplied frequencies.
