### ISSUE TITLE
Can Kats use prophet 1.0.1 instead of older fbprophet  ?

### ISSUE THREAD

**Issue by lcoulet** [facebookresearch/Kats#105]
Hi, related to other issues mentioned (downlgrade of fbprohet to 0.7 for example) why is Kats not using the version 1.0.1 of prophet (new name of fbprophet) ?

**Comment by candalfigomoro** [comment]
Duplicated https://github.com/facebookresearch/Kats/issues/62

**Comment by michaelbrundage** [comment]
duplicate of #62
