### ISSUE TITLE
Refining docs around hyperparameter (grid) search

### ISSUE THREAD

**Issue by openerror** [facebookresearch/Kats#111]
First of all, great package --- kudos to the team that created it!

I was trying to adopt the grid search code in [tutorial 201 ](https://github.com/facebookresearch/Kats/blob/master/tutorials/kats_201_forecasting.ipynb), which introduces forecasting, for my own needs. In particular, I ran into two problems --- the resolution of which may benefit from more comprehensive docs.

As an example, here is how I defined the search space for tuning the hyperparameters of `VARModel`. 

```python
parameters_grid_search = [
    {
        "name": "maxlags",
        "type": "choice",
        "values": list(range(1, 14)),
        "value_type": "int",
        "is_ordered": True
    },
]
```

First, it is unclear what are the valid options for `type`, and what different effects they have. Second, it is unclear that values **have to be** a list, not e.g., a tuple --- until I ran into an `AssertionError`.

The first one could really use input from people familiar with `kats`' tuning backend. The second perhaps can be remedied by adding a note in the tutorial notebook and/or API docs; would anyone mind me making a pull request?

**Comment by iamxiaodong** [comment]
Hi @openerror, you're more than welcome to make a PR for this, our team will review once it's ready. Thanks!
