### ISSUE TITLE
CUMSUMDetector example doesn't work

### ISSUE THREAD

**Issue by adalaza12** [facebookresearch/Kats#112]
Hi, 

Thank you very much for sharing your work!
I try to learn from Kats 202 - Detection with Kats and use it on my data, but there is an issue.
I don't manage to see what happens when I run cell 2(generating df_increase_decrease) and 3 (using CUMSUMDetector function) from Kats 202 - Detection with Kats.
Instead of having the graph that is visible in the document at the output 3,  I get this ERROR:
"view limit minimum -7.75699... is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units".

I don't know what causes this issue, I have had a look around on different forums and I can't find the solution.
I would be very happy if you could help me.

Regards,
Adriana

**Comment by jeffhandl** [comment]
HI @adalaza12,

Can you give us the steps to help reproduce this error so we can try to understand what's going on here?

Thanks!

**Comment by jeffhandl** [comment]
@adalaza12 did you forget to attach the document?

**Comment by adalaza12** [comment]
[CUMSUMDetector_error.pdf](https://github.com/facebookresearch/Kats/files/6976452/CUMSUMDetector_error.pdf)
I think it's all good now.

**Comment by jeffhandl** [comment]
Hi @adalaza12, can you give me the steps that you used to install Kats?

**Comment by adalaza12** [comment]
Since I work from my professional computer i don't have access to install new libraries, my manager did it for me.
I wanted to mention that, eventhough I have this error, the function will give me the change_points, but it won't plot them.

I tried to install the module on my laptop (with the command: pip install kats), but i have this error:
[installation-error.pdf](https://github.com/facebookresearch/Kats/files/6980606/installation-error.pdf)

Do you have the instructions for installing the library? Maybe I could give it a try on my personal laptop.

**Comment by jeffhandl** [comment]
@adalaza12 the installation instructions can be found [here](https://github.com/facebookresearch/Kats/blob/master/README.md#installation-in-python) on our README.  I definitely recommend trying them on your personal  machine.  We will take a look at your error as well.

**Comment by adalaza12** [comment]
Ok, thank you very much for your answers!
