### ISSUE TITLE
Light Install on Windows

### ISSUE THREAD

**Issue by ngupta23** [facebookresearch/Kats#115]
I am interested in using the detectors in `kats` for my project (on windows), but the current install is too heavy (requiring Prophet and PyTorch and other heavy libraries). Is there a light version install for `kats` that provides the bare bone utility functions. If not, could one be made available?

I see that `setup.py` has [some option like this](https://github.com/facebookresearch/Kats/blob/baef07f5033cc9b385609aec942e6097b31db233/setup.py#L24), but how do I enable this while installing from pip on windows?

Thanks!

**Comment by iamxiaodong** [comment]
Thanks for your interest and using Kats! @michaelbrundage added the optional installation support so that users can omit some heavy dependencies based on their purposes, please see `setup.py` for more details. Please note - you may want to install Kats from our source. Thanks!

**Comment by ngupta23** [comment]
Could an option be provided to install this form pip using something like this? I want to use the detectors from `kats` in my package but I do not want to add the complete dependency.

```
pip install kats[light]
```

If there is an alternate way to include the light version in other package dependencies, could you point me to the instructions?

**Comment by michaelbrundage** [comment]
As discussed in duplicate issue #101, we would like to provide such functionality, but `pip` doesn’t currently support subtracting dependencies like that, only adding. See #101 for the linked open issues in other repositories if you’d like to request such functionality.

**Comment by michaelbrundage** [comment]
Oh, and that issue and the current source `README.md` have the installation instructions to achieve what you desire, which is `MINIMAL=1 pip install .` from current source, and then manually  install any additional optional dependencies as neefed.

**Comment by ngupta23** [comment]
Hi @michaelbrundage . Thanks for the pointer to the duplicate issue. I already tried this and got this error on Windows. I tried setting MINIMAL in my environment variable but that did not seem to help either. Not sure what I am doing wrong here. Could you give some pointers on how to install this on Windows in minimal mode? Thanks!

![image](https://user-images.githubusercontent.com/33585645/130357433-548f6269-8642-45e7-8009-f47c50343329.png)

**Comment by michaelbrundage** [comment]
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1

**Comment by ngupta23** [comment]
@michaelbrundage, I have already tried that. It does not work.

![image](https://user-images.githubusercontent.com/33585645/130357875-53295a96-a940-4953-bad3-3c22add5d408.png)

**Comment by ngupta23** [comment]
@michaelbrundage @iamxiaodong - Do you mind opening this Issue until it is resolved on Windows? Thanks for your help with this issue.

**Comment by michaelbrundage** [comment]
Is there something different here than in #101 and #49? We’ve added the ability to have a light install (the title of this issue), and other users have also reported difficulties installing on Windows.

**Comment by ngupta23** [comment]
I think this one is slightly different. This is related to the **"MINIMAL" install on windows**. The other issues are either about a general light install option (I think your suggestion in #101 might only work on Linux) or issues with installing the full version on Windows (issues coming from installing `prophet`).

Since the MINIMAL version does not have `prophet` as a dependency, I do not think that issue (#49) is directly related. Do you have an alternate to install the light (MINIMAL) version on `windows`?

Thanks!
