### ISSUE TITLE
Kats model deployment recommendations

### ISSUE THREAD

**Issue by owoshch** [facebookresearch/Kats#117]
Thank you for your wonderful work!
I'm getting started with Kats and I'm wondering what are the best practices to deploy the Kats model?

For example, if I work with the Pytorch model I usually transfer it to TensorRT and run it in production on a CUDA-compatible device.

What are the recommendations for exporting and running Kats models?

**Comment by rohanfb** [comment]
Once fit, there shouldn't be many more additional steps to deploy a Kats model. The models themselves should be lightweight and easy to run inference on in production, similar to how you might run a standard `statsmodel` or `sklearn` model. One possible method can be to save the trained model as a file (e.g. via `pickle`) and load into your prod environment for inference as needed.
