### ISSUE TITLE
Using Kats into an existing library using the newest version of Prophet instead of fbprophet

### ISSUE THREAD

**Issue by alessandro-pinzuti** [facebookresearch/Kats#118]
Dear developers, 

we are trying to add Kats into an existing library that uses the newest version of Prophet instead of fbprophet, but we got incompatibility errors with numpy and pystan versions. 

Is it on schedule to add Prophet into Kats instead of fbprophet? 
Could you propose a way to resolve incompatibility issues?

Thanks a lot, and congratulations for the work done!

**Comment by MoKazemi9** [comment]
Hi @alessandro-pinzuti , Thank you for submitting the issue. Please see #62

**Comment by alessandro-pinzuti** [comment]
Thanks a lot @MoKazemi9!
