### ISSUE TITLE
MINIMAL=1 pip install kats installs outdated kats

### ISSUE THREAD

**Issue by abalhomaid** [facebookresearch/Kats#121]
Dear developers,

Thank you for creating a great package.

I believe Kats version on PyPi is outdated. When I tried to minimally install Kats on a new virtual environment using `MINIMAL=1 pip install kats`, it installed the `test_requirements.txt` libraries. Would you be kind enough to update the package on PyPi if this is the case?

Thank you for your time.

**Comment by iamxiaodong** [comment]
Hi @abalhomaid, thanks for your question. Yes, we have been actively developing Kats since the last PyPI version so the current library from source is quite different from the PyPI version. We will make it announcement on github when it comes to the next release. Thanks for your patience.
