### ISSUE TITLE
Tutorial "Detecting Multiple Change Points with Interest Windows" not using Interest Windows

### ISSUE THREAD

**Issue by JonasKlenk** [facebookresearch/Kats#122]
While going through the tutorial kats_202_detection.ipynb, I reused the code for "Detecting Multiple Change Points with Interest Windows".

https://github.com/facebookresearch/Kats/blob/250b4fdd019d39bf1ae9609339dbcd595b641d2b/tutorials/kats_202_detection.ipynb#L621

Though, there is a typo in the name of the Parameter. `insterest_window` instead of `interest_window`. Therefore it is ignoring the parameter.

**Comment by MoKazemi9** [comment]
@JonasKlenk , Thank you for submitting the issue and sorry for the typo, please go ahead and submit a PR.

**Comment by jeffhandl** [comment]
Thanks for pointing out this typo @MoKazemi9 !  It should be fixed by [this PR](https://github.com/facebookresearch/Kats/pull/124).
