### ISSUE TITLE
What makes Kats different from Darts?

### ISSUE THREAD

**Issue by ethantjones97** [facebookresearch/Kats#128]
Kats (https://github.com/facebookresearch/Kats) claims to be "the first comprehensive Python library to develop the standards and connect various domains in time series analysis, where the users can explore the basic characteristics of their time series data, predict the future values, monitor the anomalies, and incorporate them into their ML models and pipelines."

How is this different from Unit8's Darts (https://github.com/unit8co/darts)?

I am intrigued by Kats, since it is designed by Facebook and claims to do something novel, but I can't figure out what it does differently from Darts, which has much more example/tutorial material out there.

**Comment by iamxiaodong** [comment]
Thanks for the question, @ethantjones97. As far as I know, Darts focuses on forecasting, from their Github page: "darts is a Python library for easy manipulation and forecasting of time series". However, forecasting is only one of our current domains in Kats, beyond that, we also have extensive modules for detection and feature embedding, see more details in our tutorials especially Kats 202 and Kats 203 in https://github.com/facebookresearch/Kats/tree/main/tutorials.

We're currently working on a series of Medium posts to show more diverse functionalities of Kats, also improving our tutorials. Please let me know if you have any further questions. Thanks.

**Comment by kmedved** [comment]
Thanks. A Medium post, showing off the feature embedding capabilities of Kats in particular, would be appreciated. This looks like a very promising package in that respect.
