### ISSUE TITLE
Trying to get backtesting for VAR model

### ISSUE THREAD

**Issue by DanielVenkatesh** [facebookresearch/Kats#130]
(1) Do we need to choose parameters for VAR in grid_search? If so, what are the parameters that we have to consider from maxlogs, ic and, ctt?
(2) I tried with three parameters namely, p, q and, d. But it is resulting in error. Could you please address this issue?

multi_df = pd.read_csv("/content/example_fin.csv")
multi_ts = TimeSeriesData(multi_df, time_col_name='time', use_unix_time='True')
# example_fin.csv consists of four columns. Namely, 'time','t1','t2','t3' 
#time is in **ns**

from kats.models.var import VARModel, VARParams
params = VARParams()
m = VARModel(multi_ts, params)
m.fit()
fcst = m.predict(steps=10)
print(fcst)
m.plot()
plt.show()

import kats.utils.time_series_parameter_tuning as tune

from kats.consts import ModelEnum, SearchMethodEnum, TimeSeriesData

from kats.models.var import VARParams, VARModel

from ax.core.parameter import ChoiceParameter, FixedParameter, ParameterType

from ax.models.random.sobol import SobolGenerator

from ax.models.random.uniform import UniformGenerator
warnings.simplefilter(action='ignore')

parameters_grid_search = [
{
    "name": "p",
    "type": "choice",
    "values": list(range(1, 3)),
    "value_type": "int",
    "is_ordered": True,
},
{
    "name": "d",
    "type": "choice",
    "values": list(range(1, 3)),
    "value_type": "int",
    "is_ordered": True,
},
{
    "name": "q",
    "type": "choice",
    "values": list(range(1, 3)),
    "value_type": "int",
    "is_ordered": True,
},
]

parameter_tuner_grid = tune.SearchMethodFactory.create_search_method(
    objective_name="evaluation_metric",
    parameters=parameters_grid_search,
    selected_search_method=SearchMethodEnum.GRID_SEARCH,
)

split = int(0.8*len(multi_ts))

train_mv = multi_ts[0:split]
test_mv=multi_ts[split:]

def eval_function(params):
  var_params= VARParams(
      p=params['p'],
      d=params['d'],
      q=params['q']
  )
  model=VARModel(train_mv,var_params)
  model.fit()
  model_pred=model.predict(steps=len(test_mv))
  error=np.mean(np.abs(model_pred.values - test_mv.value.values))
  return error

parameter_tuner_grid.generate_evaluate_new_parameter_values(
    evaluation_function=eval_function //Error 
)
parameter_tuning_results_grid = (
    parameter_tuner_grid.list_parameter_value_scores()
)
parameter_tuning_results_grid

_____________________________________________________________*****************__________________________________________________________
TypeError                                 Traceback (most recent call last)
<ipython-input-26-18d161dd9352> in <module>()
      1 parameter_tuner_grid.generate_evaluate_new_parameter_values(
----> 2     evaluation_function=eval_function
      3 )
      4 
      5 parameter_tuning_results_grid = (

11 frames
<ipython-input-20-ce12ed70ac29> in eval_function(params)
     13   model.fit()
     14   model_pred=model.predict(steps=len(test_mv))
---> 15   error=np.mean(np.abs(model_pred.values - test_mv.value.values))
     16   return error

TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'float'

**Comment by rohanfb** [comment]
Hello,

The `VARParams` object allows you to specify the following params: https://facebookresearch.github.io/Kats/api/kats.models.var.html#kats.models.var.VARParams

For more information regarding these parameters and possible values, see here: https://www.statsmodels.org/stable/generated/statsmodels.tsa.vector_ar.var_model.VAR.fit.html#statsmodels.tsa.vector_ar.var_model.VAR.fit
