### ISSUE TITLE
Can I get meta-dataset in your meta-learning experiment?

### ISSUE THREAD

**Issue by 17011813** [facebookresearch/Kats#133]
Hello, I'm really glad to learn meta-learning with your paper and git code.

I tried Kats/tutorials/kats_204_metalearning.ipynb code and read the paper "Self-supervised learning for fast and scalable time series hyper-parameter tuning".
I wanna get the Facebook Infrastructure metadata and M3 metadata that you used in this paper and code.

If you can't offer those metadata, just let me know how to get Facebook Infrastructure raw time series data and M3 raw time series data.

Thanks for your kind and awesome paper and code.

**Comment by swimmingCreative** [comment]
I don't know where to get the Facebook Infrastructure metadata, but you can get M3 metadata by yourself.
The M3 data is in:
https://forecasters.org/resources/time-series-data/m3-competition/

Refer to tutorial 204, You can get metadata by yourself.

**Comment by yangbk560** [comment]
Hi @17011813, sorry that we cannot provide raw data/metadata of Facebook Infrastructure. For m3 data set, there is a file "[m3_meta_data.csv](https://github.com/facebookresearch/Kats/blob/main/kats/data/m3_meta_data.csv)" in our code base.
