### ISSUE TITLE
How to get exact outliers in Univariate Time Series using OutlierDetector? 

### ISSUE THREAD

**Issue by sthirumoorthi** [facebookresearch/Kats#139]
Hello, I'm trying to analyze the Outlier Detection framework for my project but it appears like the model returns the outlier range (not the exact index). Below are the details about my dataset.

2019-01-01 | 35
2019-01-02 | 32
2019-01-03 | 30
2019-01-04 | 31
2019-01-05 | 44
2019-01-06 | 29
2019-01-07 | 45
2019-01-08 | 43
2019-01-09 | 500
2019-01-10 | 27
2019-01-11 | 38
.....
I would expect the model to return the outlier as "500" and date as "2019-01-09". But the model returns as below.
ts_outDetection.outliers[0] ->
[Timestamp('2019-01-06 00:00:00'),
 Timestamp('2019-01-07 00:00:00'),
 Timestamp('2019-01-08 00:00:00'),
 Timestamp('2019-01-09 00:00:00'),
 Timestamp('2019-01-10 00:00:00'),
 Timestamp('2019-01-11 00:00:00'),
 Timestamp('2019-01-12 00:00:00')]

Can someone help me to understand the outlier detector concept in Kats or direct me to the reference document(if any) please?
Let me know if you need more details.
![FB Kats Issue](https://user-images.githubusercontent.com/90926526/136973311-b380f66b-65e7-4308-8c12-c011660d5120.png)

**Comment by sanelemahlalela** [comment]
I think @sthirumoorthi is asking why the detector returns the index  (`time`  column) , instead of the value (`value` column) on his data set. If this is the case @sthirumoorthi , I think that you are better off getting back the index. With the index then you can find the value on your copy of the dataset. Incase you have multiple rows with that particular `value`, in  this case `500`, then, you'll receive multiple indexes.  This is my understanding. I might be wrong

**Comment by sthirumoorthi** [comment]
Hi @sanelemahlalela.. Getting the value or index is not a problem. The model returns range of values/indexes or multiple values/indexes instead of returning the outliers. In the above example, the model returns the below timestamps as outliers wherein i was expecting only one timestamp ('2019-01-09 00:00:00') as outlier (value '500').

ts_outDetection.outliers[0] ->
[Timestamp('2019-01-06 00:00:00'),
Timestamp('2019-01-07 00:00:00'),
Timestamp('2019-01-08 00:00:00'),
Timestamp('2019-01-09 00:00:00'),
Timestamp('2019-01-10 00:00:00'),
Timestamp('2019-01-11 00:00:00'),
Timestamp('2019-01-12 00:00:00')]

As per my understanding, we don't have any hyper-parameters to adjust (except iqr_mul) to increase the accuracy of the model. So i wanted to understand how the outlier detection logic works for this model and what needs to be done to detect the exact outliers.
