### ISSUE TITLE
acf() got an unexpected keyword argument 'unbiased'

### ISSUE THREAD

**Issue by aron-alarik** [facebookresearch/Kats#140]
created a time kats series object, after hours of trying to install it on my system, now getting this error:

![image](https://user-images.githubusercontent.com/86116123/137129975-744e753c-6de7-4062-86bb-4d13df6072b9.png)

**Comment by aron-alarik** [comment]
THanks again ! Sounds like fun !!

**Comment by michaelbrundage** [comment]
two other options, if you don't want to install Kats from source for some reason:

* downgrade `statsmodels` to a version before they removed this parameter (I think 0.12.2?)
* wait for the next Kats release.
