### ISSUE TITLE
Local editable install fails with dependency conflict

### ISSUE THREAD

**Issue by ourownstory** [facebookresearch/Kats#142]
Trying to install Kats in a new venv as --editable fails with dependency conflict.
Steps to reproduce:
```
git clone https://github.com/facebookresearch/Kats.git
cd Kats
pip install --editable .
```
Results in the following error:
```
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of ax-platform to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of kats to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install kats and kats==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    kats 0.1.0 depends on torch<1.7.0
    botorch 0.3.2 depends on torch>=1.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
Why this matters: I am planning to use Kats within another package and will need to make changes to Kats in the process, which I plan to contribute back to Kats if they are successful/useful. Thus, I want a locally editable install of (my fork of) Kats, tracked by git.

**Comment by ourownstory** [comment]
Solved this with a hacky workaround:

First, I edited the `test_requirements.txt` to not specify a version for `torch`.

Second, I installed the most recent torch version `pip install torch`

Finally, the install works without issues `pip install --editable .`

Evidently, the first step should not need be done.

**Comment by michaelbrundage** [comment]
I have a fix pending which changes `test_requirements.txt` to allow torch <= 1.8.1. torch 1.9.0 currently has incompatibilities with other dependences. I filed a separate internal issue for updating `CONTRIBUTING.md` with more detailed instructions.
