### ISSUE TITLE
How to add external regressors to kats prophet models for multivariate forecasting?

### ISSUE THREAD

**Issue by riteshchhetri10** [facebookresearch/Kats#167]
Hey, a great toolkit that you've developed out there. 
Just wanted to know the process to add external regressors for multivariate forecasting.
 I am working on the Seattle Gilman trail dataset ( ~ 52.6K rows ) with 5 columns. 

I came across the following issue as a reference  for the functionality on the FB prophet repo. 
https://github.com/facebook/prophet/issues/101

**Comment by yangbk560** [comment]
Hi @riteshchhetri10, here is a snippet of example code of including external regressors:

`from kats.models.prophet import ProphetModel, ProphetParams

air_passengers_ts = TimeSeriesData(air_passengers_df)
reg = np.random.randn(len(air_passengers_ts))

pparams = ProphetParams(extra_regressors = [{'value': reg, 'name':'reg1'}])

pmodel = ProphetModel(data=air_passengers_ts, params=pparams)

pmodel.fit()

pmodel.predict(steps=20, extra_regressors = [{'value': np.random.randn(20), 'name':'reg1'}])`
