### ISSUE TITLE
Unable to fit the SARIMA model for multivariate dataset, despite providing exogenous regressors?

### ISSUE THREAD

**Issue by riteshchhetri10** [facebookresearch/Kats#168]
I have been trying multivariate time series forecasting on the Seattle Gilman trail dataset(52.6k rows) however, even after providing the exogenous regressors I have been unable to fit the SARIMA model on it. I have attached the screenshots of the error below.  The code used is similar to the solution given in : https://github.com/facebookresearch/Kats/issues/96

I have been training this dataset in a Kaggle notebook.

![issue_1](https://user-images.githubusercontent.com/46395515/140905561-60143212-fb98-4652-81fd-aae207c411e8.JPG)
![issue_2](https://user-images.githubusercontent.com/46395515/140905557-880f6d8b-8bae-47fa-9815-5eff65d0f10c.JPG)

**Comment by yangbk560** [comment]
Hi @riteshchhetri10, sorry that Kats SARIMA currently does not support multivariate time series forecasting.

**Comment by riteshchhetri10** [comment]
Ok. Thanks for Clarifying!
