### ISSUE TITLE
Python Poetry error: PackageInfo: Invalid constraint (scikit-learn (>+0.24.2))

### ISSUE THREAD

**Issue by JasperHG90** [facebookresearch/Kats#172]
I use [python Poetry](https://python-poetry.org/) to manage dependencies.

When installing Kats, I see:

```shell
poetry add git+https://github.com/facebookresearch/Kats.git
PackageInfo: Invalid constraint (scikit-learn (>+0.24.2)) found in kats-0.1.0 dependencies, skipping
<debug>PackageInfo:</debug> Invalid constraint (scikit-learn (>+0.24.2)) found in kats-0.1.0 dependencies, skipping
```

This happens because of [the following](https://github.com/facebookresearch/Kats/blob/main/requirements.txt#L7) specification in the requirements. I'm not familiar with this syntax. Is it a typo and, if not, is it absolutely necessary? 

Thanks!

**Comment by michaelbrundage** [comment]
This was fixed in 49b341c7f658b8c5c4603aa95dc995ffd608008b
