### ISSUE TITLE
Unable to install Kats

### ISSUE THREAD

**Issue by neldivad** [facebookresearch/Kats#174]
I've tried the `pip install kats` method, returns a wall of errors 

```
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-tjpsqluy\\fbprophet_adc48eacd16347cca677714cedac55a0\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-tjpsqluy\\fbprophet_adc48eacd16347cca677714cedac55a0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-9kozjt8t'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-tjpsqluy\fbprophet_adc48eacd16347cca677714cedac55a0\
  Complete output (284 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_f5236004a3fd5b8429270d00efcc0cf9 NOW.
  WARNING:pystan:MSVC compiler is not supported
  stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_1081474144516276025.cpp
  C:\Users\User\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
```

Also tried the `conda install -c conda-forge kats` method, returns: 
```
(base) C:\Users\User>conda install -c conda-forge kats
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
Pystan version is 2.19.1.1

Fbprophet version is 0.7.1

**Comment by orthosku** [comment]
I have this same error. Tried in various different virtual envs 3.8-3.10.

**Comment by SakshiNYCU** [comment]
Was anyone able to solve this error?

**Comment by SakshiNYCU** [comment]
> I've tried the `pip install kats` method, returns a wall of errors
> 
> ```
> ERROR: Command errored out with exit status 1:
>    command: 'C:\Users\User\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-tjpsqluy\\fbprophet_adc48eacd16347cca677714cedac55a0\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-tjpsqluy\\fbprophet_adc48eacd16347cca677714cedac55a0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-9kozjt8t'
>        cwd: C:\Users\User\AppData\Local\Temp\pip-install-tjpsqluy\fbprophet_adc48eacd16347cca677714cedac55a0\
>   Complete output (284 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib
>   creating build\lib\fbprophet
>   creating build\lib\fbprophet\stan_model
>   INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_f5236004a3fd5b8429270d00efcc0cf9 NOW.
>   WARNING:pystan:MSVC compiler is not supported
>   stanfit4anon_model_f5236004a3fd5b8429270d00efcc0cf9_1081474144516276025.cpp
>   C:\Users\User\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
> ```
> 
> Also tried the `conda install -c conda-forge kats` method, returns:
> 
> ```
> (base) C:\Users\User>conda install -c conda-forge kats
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: -
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> ```
> 
> Pystan version is 2.19.1.1
> 
> Fbprophet version is 0.7.1

Were you able to solve this error? If yes can you please share how?

**Comment by orthosku** [comment]
Nope I wasn’t able to solve it. Moved over to darts. It worked for me on Colab but then the kernal crashes when I try to train my model.

**Comment by michaelbrundage** [comment]
Kats is now on 0.2.0. Resolving old 0.1.0 installation issues.

**Comment by msbeeman** [comment]
Getting same error here on two different macs, both on monterey. One using m1 chip, the other using the older i7.

**Comment by rjpaxtondata** [comment]
same here

**Comment by TheUruguayo** [comment]
The installation process fails on my mac, on my windows and inside colab using the tutorials inside the folder.
