### ISSUE TITLE
NotImplemented error during Ensembling

### ISSUE THREAD

**Issue by akrishnamo** [facebookresearch/Kats#175]
In the forecasting notebook example, for ensembling the KatsEnsemble m.fit() runs into an error. Removing the  Arima model escapes the error. Is this a version issue / how to fix?

Here is the traceback.

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-44-2381acbb9ce7> in <module>()
     50 
     51 # fit and predict
---> 52 m.fit()
     53 
     54 # predict for the next 30 steps

3 frames
/usr/local/lib/python3.7/dist-packages/kats/models/ensemble/kats_ensemble.py in fit(self)
    358                 data=desea_data,
    359                 models=model_params,
--> 360                 should_auto_backtest=auto_backtesting,
    361             )
    362         else:

/usr/local/lib/python3.7/dist-packages/kats/models/ensemble/kats_ensemble.py in fitExecutor(self, data, models, should_auto_backtest)
    310         pool.close()
    311         pool.join()
--> 312         fitted = {model: res.get() for model, res in fitted_models.items()}
    313 
    314         # if auto back testing

/usr/local/lib/python3.7/dist-packages/kats/models/ensemble/kats_ensemble.py in <dictcomp>(.0)
    310         pool.close()
    311         pool.join()
--> 312         fitted = {model: res.get() for model, res in fitted_models.items()}
    313 
    314         # if auto back testing

<string> in get(self, *args, **kwds)

/usr/lib/python3.7/multiprocessing/managers.py in _callmethod(self, methodname, args, kwds)
    832             dispatch(conn, None, 'decref', (token.id,))
    833             return proxy
--> 834         raise convert_to_error(kind, result)
    835 
    836     def _getvalue(self):

NotImplementedError: 
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been removed in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and statsmodels.tsa.SARIMAX.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained. It also offers alternative specialized
parameter estimators.

**Comment by rohanfb** [comment]
The updated notebooks should no longer have this error. Please also ensure that your `statsmodels` version is `0.12.2` as specified in our `requirements.txt`.
