### ISSUE TITLE
Tutorials do not run

### ISSUE THREAD

**Issue by soazarta** [facebookresearch/Kats#183]
The files: kats_201_forecasting.ipynb and kats_101_basics.ipynb crashes half way running into the notebook. I ran them on google collobatory. There are numerous errors on 201_forecasting. I provided an example of one of the errors.

Finding the errors should be easy, just !pip install kats, and then run the tutorials,.

Thank you very much for providing us this resource, excited to use it when it works.

![image](https://user-images.githubusercontent.com/47881567/147530696-0bfde925-04f0-4596-b336-7237457b6183.png)

**Comment by eRuaro** [comment]
I'm also running into this error, care to mention how to fix this @michaelbrundage @iamxiaodong ?

**Comment by justinkuan** [comment]
I had a similar error.  The problem lies in kats, which needs to be updated for the newer version of statsmodel.  The missing y is because y was deprecated and removed in 0.13(?).  Try installing the version specified in requirements.txt (statsmodels==0.12.2) and see if that resolves the problem.

**Comment by rohanfb** [comment]
This issue should be fixed with kats 0.2.0 and the updated tutorial notebooks. Please reopen if it persists. Thanks.
