### ISSUE TITLE
!! ValueError: freq T not understood. Please report if you think this is in error.

### ISSUE THREAD

**Issue by Aditya701** [facebookresearch/Kats#185]
ERROR:root:!! Traceback (most recent call last):
!!   File "/usr/local/lib/python3.7/dist-packages/kats/detectors/outlier.py", line 114, in detector
    outlier = self.__clean_ts__(ts)
!!   File "/usr/local/lib/python3.7/dist-packages/kats/detectors/outlier.py", line 88, in __clean_ts__
    result = seasonal_decompose(original, model=self.decomp)
!!   File "/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/seasonal.py", line 156, in seasonal_decompose
    pfreq = freq_to_period(pfreq)
!!   File "/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py", line 815, in freq_to_period
    "think this is in error.".format(freq)
!! ValueError: freq T not understood. Please report if you think this is in error.

ERROR:root:Outlier Detection Failed

**Comment by swimmingCreative** [comment]
Hi @Aditya701, can you upload you time series?

**Comment by Aditya701** [comment]
[ec2_cpu_utilization_5f5533.csv](https://github.com/facebookresearch/Kats/files/7827592/ec2_cpu_utilization_5f5533.csv)

**Comment by yangbk560** [comment]
Hi @Aditya701, I think the problem stems from statsmodels design like mentioned in https://github.com/statsmodels/statsmodels/issues/2856. I would suggest explicitly specifying the seasonality as integer (like 12 for monthly data). Feel free to let us know if this solves your problem. Thanks!
