### ISSUE TITLE
GetMetaData searches hyperparameters that is out of the bounds of the time series data

### ISSUE THREAD

**Issue by yowgwowang** [facebookresearch/Kats#188]
When I'm using GetMetaData with stlf model, it keep selecting hyperparameter (seasonality: m) that is larger than the length of the time seires.

Can we add some fail-safes to resolve the issue? or can I set a range of parameters in the GetMetaData's all_params setting so it will only search hyperparameters make sense?

ValueError: The seasonality length m must be smaller than the length of time series

![image](https://user-images.githubusercontent.com/66694357/148714795-5112cbb7-8d1c-43a2-adcd-cc91dcb6a18b.png)
![image](https://user-images.githubusercontent.com/66694357/148714828-aea1be97-7543-4795-9805-6c321ce92891.png)
![image](https://user-images.githubusercontent.com/66694357/148714862-ed13c496-7988-4001-af59-622dc7421ff4.png)
![image](https://user-images.githubusercontent.com/66694357/148714882-c982c8ff-1d36-440d-9229-2ee5fdc63a4d.png)
![image](https://user-images.githubusercontent.com/66694357/148714894-c85b4d55-5268-4ff1-ab10-438e3418daef.png)
![image](https://user-images.githubusercontent.com/66694357/148714916-ad0b64ff-f23e-4c66-9aa6-ea260b0c8008.png)
![image](https://user-images.githubusercontent.com/66694357/148714934-834d1381-a876-4802-bcd5-e4bc6d122bb6.png)
![image](https://user-images.githubusercontent.com/66694357/148714958-85199103-5a43-45d4-9275-b45e50665187.png)

**Comment by yangbk560** [comment]
Hi @yowgwowang, we have landed a fix to make the models fail-safe. We will work on the feature allowing customized parameter space. Thank you so much for the feedback. :)
