### ISSUE TITLE
Error installing with MINIMAL_KATS=1 using pip

### ISSUE THREAD

**Issue by arisliang** [facebookresearch/Kats#193]
Seems it tries to build fbprophet, even though it's already installed.

>Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ly\miniconda3\envs\ts3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ly\\AppData\\Local\\Temp\\pip-install-i4iickh0\\fbprophet_b07e546e889c40ccb5b87df726372596\\setup.py'"'"'; __file__='"'"'C:\\Users\\ly\\AppData\\Local\\Temp\\pip-install-i4iickh0\\fbprophet_b07e546e889c40ccb5b87df726372596\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ly\AppData\Local\Temp\pip-wheel-mpsar8bx'
       cwd: C:\Users\ly\AppData\Local\Temp\pip-install-i4iickh0\fbprophet_b07e546e889c40ccb5b87df726372596\
  Complete output (8 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  error: Could not find module 'C:\Users\ly\miniconda3\envs\ts3\lib\site-packages\scipy\.libs\libbanded5x.CBCBXIAYFUWOYCSBXUA2BT6W76FYX4C7.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet, ax-platform, kats
  Attempting uninstall: fbprophet
    Found existing installation: fbprophet 0.7.1
    Uninstalling fbprophet-0.7.1:
      Successfully uninstalled fbprophet-0.7.1
    Running setup.py install for fbprophet ... error

Windows 10, python 3.8

**Comment by michaelbrundage** [comment]
Hi @arisliang, I think this was fixed in c501da1d49313c12616ff06297b221d80cd36f57.
