### ISSUE TITLE
Multivariate Anomaly Detector returns strange errors

### ISSUE THREAD

**Issue by hanhanwu** [facebookresearch/Kats#194]
I tried to run the same code as the tutorial here: https://github.com/facebookresearch/Kats/blob/main/tutorials/kats_202_detection.ipynb
![input](https://user-images.githubusercontent.com/4024769/150076040-a493b0ba-60c5-498e-beb0-64b7ebe213be.png)

But got errors like this:
![error](https://user-images.githubusercontent.com/4024769/150076078-5b9c4887-18d7-4294-aaec-ddb9b992cfbe.png)

The error doesn't make sense to me, since my data input are just days like this:
![data](https://user-images.githubusercontent.com/4024769/150076148-6e76ca37-2da3-4eb0-af52-eeecdb21015a.png)

Do you know how to fix this issue?

**Comment by rohanfb** [comment]
It seems as though your data may have microsecond level frequency. Does adjusting it to day level frequency help?

**Comment by hanhanwu** [comment]
Not really, my data is just YYYY-MM-DD format like what's shown above.... That's why I felt the error had no sense~

**Comment by rohanfb** [comment]
Are you using the `multivariate_anomaly_simulated.csv` dataset?

**Comment by hanhanwu** [comment]
Yes, I tried the same code and same data as Kats tutorial: https://github.com/facebookresearch/Kats/blob/main/tutorials/kats_202_detection.ipynb, and got this error.
Previously I also tried with my own timeseries data, still had this error. Not sure why

**Comment by rz5q** [comment]
I encountered the same error today and figured out it is caused by a line of code in the outlier.py in the Kats library.
I fix the problem by replacing the line "freq = time_diff.unique()[0].astype("int")" with
            "freq = int(time_diff.unique()[0])", then it works. Hope this can help.

**Comment by hanhanwu** [comment]
I made the same change, this error was gone. But for my data, I got new error saying "frequency not constant...". Anyway, I finally implemented my own VAR anomaly detector on multivariate ts and it works better. So, never mind. Thank you!
