### ISSUE TITLE
error when execute OutlierDetector.detector()

### ISSUE THREAD

**Issue by SoarAnyway** [facebookresearch/Kats#202]
when I run 
`ts_outlierDetection = OutlierDetector(ts, "additive")`
`ts_outlierDetection.detector()`

then raise

ERROR:root:!! Traceback (most recent call last):
!!   File "/home/ubuntu/anaconda3/envs/pycaret/lib/python3.7/site-packages/kats/detectors/outlier.py", line 114, in detector
    outlier = self.__clean_ts__(ts)
!!   File "/home/ubuntu/anaconda3/envs/pycaret/lib/python3.7/site-packages/kats/detectors/outlier.py", line 88, in __clean_ts__
    result = seasonal_decompose(original, model=self.decomp)
!!   File "/home/ubuntu/anaconda3/envs/pycaret/lib/python3.7/site-packages/statsmodels/tsa/seasonal.py", line 156, in seasonal_decompose
    pfreq = freq_to_period(pfreq)
!!   File "/home/ubuntu/anaconda3/envs/pycaret/lib/python3.7/site-packages/statsmodels/tsa/tsatools.py", line 815, in freq_to_period
    "think this is in error.".format(freq)
!! ValueError: freq T not understood. Please report if you think this is in error.

ERROR:root:Outlier Detection Failed

**Comment by rohanfb** [comment]
See https://github.com/facebookresearch/Kats/issues/185. This should resolve your issue.
