### ISSUE TITLE
unable to install kats on windows and rhel7 could anyone please help thanks in advance....

### ISSUE THREAD

**Issue by sai9010** [facebookresearch/Kats#205]
![image](https://user-images.githubusercontent.com/48473307/154428591-14e51e5c-10e0-44b6-ad3b-01a80cd73417.png)
![image](https://user-images.githubusercontent.com/48473307/154427076-d18165aa-cdb0-42f6-b7e2-cf362d8ea6a3.png)
![image](https://user-images.githubusercontent.com/48473307/154427213-9095225e-78dc-477a-a310-d9473fead1d5.png)
![image](https://user-images.githubusercontent.com/48473307/154427361-a43acd3c-f5ab-4d9a-9038-d3b04705b358.png)
![image](https://user-images.githubusercontent.com/48473307/154427669-a9c12ec5-e994-4691-ada8-18a59c32c263.png)
![image](https://user-images.githubusercontent.com/48473307/154427776-e91e2540-19cb-469d-b601-2abdfdf3bd00.png)
![image](https://user-images.githubusercontent.com/48473307/154427918-39bb43a1-8814-4a81-8d38-d4bf705f1991.png)

**Comment by iamxiaodong** [comment]
@sai9010 - fbprophet installation on Windows requires some additional steps, see details in https://github.com/facebook/prophet#windows-1

Please note - we just released the `v0.2.0` version, so please try to install this version and see if it works; if not, please follow the fbprophet instruction to install the `v0.7.1` prophet before install Kats. 

In the meanwhile, our team is going to make Kats available through `conda` install, which will be much easier for Windows machines in the future, I'll update here as well once it's available.
