### ISSUE TITLE
Add Neural Prophet to the KATS metalearner

### ISSUE THREAD

**Issue by nlaptev** [facebookresearch/Kats#206]
Metalearner allows for auto picking of relevant forecasting models. 

While NeuralProphet (https://github.com/ourownstory/neural_prophet) is part of KATS, it is currently not included as part of the metalearner. 

The problem for this task is to incorporate NeuralProphet as part of KATS metalearner (https://github.com/facebookresearch/Kats/tree/main/kats/models/metalearner)

**Comment by yangbk560** [comment]
Currenlty metalearner modules support neural prophet (but this model is not directly included as default models).
