### ISSUE TITLE
Multivariate Anomaly Detector - Fitted Covariance matrix is not positive definite

### ISSUE THREAD

**Issue by mateuszkowalskianalytics** [facebookresearch/Kats#210]
I would like to use Multivariate Anomaly Detector  to my date set, I have around 1000 time series. I created segments based on some variables, and  then I wanted to run the model. In some cases I got this error: **"Fitted Covariance matrix at time ... is not positive definite"** error. I know there are several techniques for transform to positive defined matrix. But my question is: is there any way to manipulate the input to avoid this error? e.g. removing correlated series etc?
I am looking for the fastest solution. 

Thanks !

**Comment by fwfichtner** [comment]
@mateuszkowalskianalytics can you share how you solved it?
