### ISSUE TITLE
kats 0.1.0 does not provide the extra 'all' or 'prophet'

### ISSUE THREAD

**Issue by OrenBochman** [facebookresearch/Kats#212]
the documentation at 

https://github.com/facebookresearch/Kats/blob/main/tutorials/kats_101_basics.ipynb at section 2.1 suggests one could and should use 

pip install kats[prophet] 
or 
pip install kats[all]

but these commands return the following messages respectively:

kats 0.1.0 does not provide the extra 'prophet'

kats 0.1.0 does not provide the extra 'all'

**Comment by iamxiaodong** [comment]
Hello @OrenBochman, this tutorial is updated to prepare for our upcoming release, which is not available yet. I'll update here once the new version is available. Thanks.

**Comment by iamxiaodong** [comment]
@OrenBochman: we just updated our library to `v0.2.0`, please install this version and see if it works. Thanks.
