### ISSUE TITLE
Error while importing CUSUM Detector from Kats

### ISSUE THREAD

**Issue by 40003552** [facebookresearch/Kats#214]
While trying to import the CUSUM Detector using the command - 'from kats.detectors.cusum_detection import CUSUMDetector', I am getting the following error message:

cannot import name 'outcome_constraint_from_str' from 'ax.service.utils.instantiation'

**Comment by iamxiaodong** [comment]
Please see the comment in https://github.com/facebookresearch/Kats/issues/216#issuecomment-1067029938
Thanks!
