### ISSUE TITLE
cannot import name 'outcome_constraint_from_str' from 'ax.service.utils.instantiation' error

### ISSUE THREAD

**Issue by saswatamukherjee14** [facebookresearch/Kats#215]
**'cannot import name 'outcome_constraint_from_str' from 'ax.service.utils.instantiation'** issue popping up on Databricks Python at the following command - from 'kats.detectors.cusum_detection import CUSUMDetector'

**Comment by iamxiaodong** [comment]
This is due to a recent change on `ax-platform` library, see comment in anther thread, thanks.
https://github.com/facebookresearch/Kats/issues/216#issuecomment-1067029938
