### ISSUE TITLE
Getting forecast horizon in GetMetaData

### ISSUE THREAD

**Issue by mjt91** [facebookresearch/Kats#217]
Started using the metalearning framework presented in 
https://github.com/facebookresearch/Kats/blob/main/tutorials/kats_204_metalearning.ipynb

Asking myself how the predictablity is calculated when you dont set the steps i.e. the forecasting horizon for the cross-validation?
How to interpret the resulting best models in the `metadata_df` column `hpt_res` then? I guess there could be way better models for short term vs long term forecast horizons for instance, or do I get something wrong?

**Comment by yangbk560** [comment]
Hi @mjt91, thanks for the question! Currently we use 80% of all data as training data and evaluate the forecasting model on the left 20% data. In other words, the `hpt_res` represents the hyper-parameters of the best candidate models evaluated on the latest 20% data.
