### ISSUE TITLE
AttributeError: 'pandas._libs.properties.CachedProperty' object has no attribute 'func'

### ISSUE THREAD

**Issue by dreldrel** [facebookresearch/Kats#224]
Hi there,

I face an error when I run m.fit() on the "Forecasting with Ensemble model" section.
![image](https://user-images.githubusercontent.com/45089360/160261601-6f03ef03-3972-43f9-9ed5-bc37a84f9902.png)

Could please anyone share how to address it?

Many thank

**Comment by dreldrel** [comment]
I found the issue is from BaseModelParams("prophet", prophet.Prophet Params()). But I still don't know why (The "prophet" package has been successfully imported)

**Comment by iamxiaodong** [comment]
Hello @dreldrel, can you share a notebook example that can reproduce this error? please also let me know the `kats` and `prophet` version numbers in your environment. Thanks.

**Comment by dreldrel** [comment]
Hi @iamxiaodong,

Thanks for getting back to me. The sample code I ran and the package version is shown below.   

`kats`: 0.2.0
`prophet`: 1.0.1
`Python`:  3.9.7

```
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore')

from kats.consts import TimeSeriesData

air_passengers_df = pd.read_csv("https://raw.githubusercontent.com/facebookresearch/Kats/main/kats/data/air_passengers.csv")

# Note: If the column holding the time values is not called time, you will want to specify the name of this column.
air_passengers_df.columns = ["time", "value"]
air_passengers_ts = TimeSeriesData(air_passengers_df)

from kats.models.ensemble.ensemble import EnsembleParams, BaseModelParams
from kats.models.ensemble.kats_ensemble import KatsEnsemble
from kats.models import (
    arima,
    holtwinters,
    linear_model,
    prophet,  # requires fbprophet be installed
    quadratic_model,
    sarima,
    theta,
)

model_params = EnsembleParams(
            [
                BaseModelParams("arima", arima.ARIMAParams(p=1, d=1, q=1)),
                BaseModelParams(
                    "sarima",
                    sarima.SARIMAParams(
                        p=2,
                        d=1,
                        q=1,
                        trend="ct",
                        seasonal_order=(1, 0, 1, 12),
                        enforce_invertibility=False,
                        enforce_stationarity=False,
                    ),
                ),
                BaseModelParams("prophet", prophet.ProphetParams()),  # requires fbprophet be installed
                BaseModelParams("linear", linear_model.LinearModelParams()),
                BaseModelParams("quadratic", quadratic_model.QuadraticModelParams()),
                BaseModelParams("theta", theta.ThetaParams(m=12)),
            ]
        )

KatsEnsembleParam = {
    "models": model_params,
    "aggregation": "median",
    "seasonality_length": 12,
    "decomposition_method": "multiplicative",
}

m = KatsEnsemble(
    data=air_passengers_ts,
    params=KatsEnsembleParam
    )

m.fit()
```

**Comment by rohanfb** [comment]
@dreldrel I think I know what the issue might be, but can you first provide the version of pandas you are using?

**Comment by dreldrel** [comment]
@rohanfb yeah, no problems. my current pandas version is 1.4.1

**Comment by rohanfb** [comment]
@dreldrel Seems like this may be an incompatibility issue between pandas and statsmodels 0.12.2. Can you try downgrading your pandas version to 1.2.x and see if that fixes it? If it does, I'll update our requirements.txt file accordingly.

**Comment by michaelbrundage** [comment]
Kats requires `pandas` <= 1.3.5. From `requirements.txt`:
`pandas>=1.0.4,<=1.3.5`

**Comment by dreldrel** [comment]
Hi there, thanks for all your kind assistance. It's now working
