### ISSUE TITLE
Monitor globalmodel training process through tensorboard?

### ISSUE THREAD

**Issue by yowgwowang** [facebookresearch/Kats#231]
Hi

Thanks for adding global model in to the Kats library.

I have a dataset with ~500k data points and I want to leverage globalmodel. However, I can't find a way to monitor the progress during model training. Is there a plan to add tensorboard capability to the globalmodel?

thank you

**Comment by yangbk560** [comment]
Hi @yowgwowang, thank you so much for asking. However, currently we do not have an immediate plan to add tensorboard capability, but you are more than welcome to contribute! The logging info of each epoch could give some information if needed.
