### ISSUE TITLE
Save serialized prophet model

### ISSUE THREAD

**Issue by rosalinesway** [facebookresearch/Kats#242]
Hi,

I tried using the kats package with the [default](https://facebook.github.io/prophet/docs/additional_topics.html#updating-fitted-models) prophet functions to serialize the prophet model using the below code:
```python
from kats.models.prophet import ProphetModel, ProphetParams
import json
from prophet.serialize import model_to_json, model_from_json
# create a model param instance
params = ProphetParams(seasonality_mode=args.seasonality_mode)  # additive mode gives worse results
m = ProphetModel(DATA_DF, params)
m.fit()
save_model(m, 'serialized_model.json')

def save_model(model, file_name):
    with open(file_name, 'w') as file:
        json.dump(model_to_json(model), file)
```
Currently, it is throwing this error:
```bash
Traceback (most recent call last):
  File "kats_example.py", line 67, in save_model
    json.dump(model_to_json(model), file)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/prophet/serialize.py", line 56, in model_to_json
    if model.history is None:
AttributeError: 'ProphetModel' object has no attribute 'history'
```

**Comment by ruisi-su** [comment]
@neelabalan I ran the same command as you showed, and the same error occurred `AttributeError: 'ProphetModel' object has no attribute 'history'`

**Comment by rosalinesway** [comment]
@neelabalan I ran the same command as you showed, and the same error occurred AttributeError: 'ProphetModel' object has no attribute 'history'

**Comment by neelabalan** [comment]
![screenshot_kats](https://user-images.githubusercontent.com/41639065/171235221-66ef2598-2047-40e3-a77a-8e319e13aa36.png)
![json_kats](https://user-images.githubusercontent.com/41639065/171235203-aa208dda-b5c8-4b67-a22c-953498d0b279.png)

**Comment by rosalinesway** [comment]
ok, I think what breaks is using the `ProphetModel` from the result of the [backtester](https://github.com/facebookresearch/Kats/blob/7547e25b9b3f181bcc1c8e969f8efeabd395a986/kats/utils/backtesters.py#L871).

```
ALL_ERRORS = ["mape", "smape", "mae", "mase", "mse", "rmse"]
    backtester_prophet = CrossValidation(
        error_methods=ALL_ERRORS,
        data=DATA_TS,
        params=params,
        train_percentage=50,
        test_percentage=20,
        model_class=ProphetModel,
        num_folds=10,
    )
    backtester_prophet.run_cv()

    backtester_errors["prophet"] = {}
    for error, value in backtester_prophet.errors.items():
        backtester_errors["prophet"][error] = value

    # results: List of tuples
    # (training_data, testing_data, trained_model, forecast_predictions)
    (
        train_data,
        test_data,
        trained_model,
        forecast_predictions,
    ) = backtester_prophet.results[0]

**Comment by rosalinesway** [comment]
@neelabalan that did work, thanks!
