### ISSUE TITLE
No selected backends had an implementation for this function.

### ISSUE THREAD

**Issue by matheusdias1996** [facebookresearch/Kats#250]
Whenever I try to run TsFeatures().transform() on a TimeSeriesData object (series or dataframe) I get this error: "No selected backends had an implementation for this function." I am attaching a picture of my notebook.

**Comment by MoKazemi9** [comment]
Hi @matheusdias1996 , Thank yo u for the issue, we are working on this issue and will be resolved soon.

**Comment by jeffhandl** [comment]
@matheusdias1996 did you mean to attach something here?

**Comment by mattdias96** [comment]
Hey Jeff,

I forgot to attach the picture, but @iamxiaodong helped me with this, so I think we can close the issue
