### ISSUE TITLE
Support for python 3.9

### ISSUE THREAD

**Issue by dakilasera** [facebookresearch/Kats#257]
Hi,

Do you have any plans on upgrading for python 3.9 any sooner?

**Comment by michaelbrundage** [comment]
FWIW, I've been using Kats on Python 3.9.9 without issues.

**Comment by michaelbrundage** [comment]
Fixed in f94b90afb5754da86fbba65c0d3a7a11979f6e0b

**Comment by dakilasera** [comment]
requirements.txt should be updated for 3.9

"importlib_metadata; python_version < '3.8'"

**Comment by michaelbrundage** [comment]
PRs welcome :)
