### ISSUE TITLE
What parameters can be used for specify change directions in bayesian and robust changepoint detection models?

### ISSUE THREAD

**Issue by jscanass** [facebookresearch/Kats#259]
Hi there! In the detection tutorial [notebook](https://github.com/facebookresearch/Kats/blob/main/tutorials/kats_202_detection.ipynb) it is shown for the `CUSUMDetector` model a parameter, `change_directions`, for specifying what type of change to be detected. What is the analogous parameter in the case of `BOCPDetector`, and `RobustStatDetector`? Or in which other form I can specify an increase or decrease? A working example could be the same as the tutorial.

**Comment by jeffhandl** [comment]
@jscanass There is not a straightforward way to pre-specify the change direction in either of these detectors.  For these detectors you will need to calculate all change points and then filter afterwards if you wish.
