### ISSUE TITLE
Can't install Kats on Fedora 36. 

### ISSUE THREAD

**Issue by konsbn** [facebookresearch/Kats#262]
I am unable to install Kats on my machine using pip. My system configurations are as below
```
OS: Arch Linux x86_64
Kernel: 5.19.8-arch1-1
```
[ this is the error I am getting after running `pip install kats`]( https://gist.github.com/konsbn/f764922cb256b8c8fa74a3bc0833f742)

**Comment by michaelbrundage** [comment]
Hi @konsbn, this is not a Kats issue. You're having troubles installing `numpy`.

```
× Encountered error while trying to install package.
2022-09-14T16:02:09,899   ╰─> numpy
```

**Comment by konsbn** [comment]
But numpy is properly installed. I use it almost daily

**Comment by konsbn** [comment]
> Hi @konsbn, this is not a Kats issue. You're having troubles installing `numpy`.
> 
> ```
> × Encountered error while trying to install package.
> 2022-09-14T16:02:09,899   ╰─> numpy
> ```

Numpy is properly installed on my system and working perfectly

**Comment by michaelbrundage** [comment]
I don't know what to tell you; the logs you posted clearly show `numpy` failed to install.

**Comment by konsbn** [comment]
> I don't know what to tell you; the logs you posted clearly show `numpy` failed to install.

Any clues/ideas on how to deal with it?
