### ISSUE TITLE
Statsmodel version issue

### ISSUE THREAD

**Issue by madhuri1991** [facebookresearch/Kats#264]
Hi, I ran into multiple issues while running the KatsEnsemble function. I read in closed issues that statsmodels version ==0.12.2 currently supports the Kats package. Although, when I tried to downgrade the statsmodels version from 0.13.2 I'm getting below error. 
![Screen Shot 2022-09-21 at 2 42 22 PM](https://user-images.githubusercontent.com/14282972/191615782-f2379e7c-6cad-41ec-9770-ef98e6f971ef.png)

**Comment by michaelbrundage** [comment]
That's quite a strange-looking error message, given it contains 0.12.2 in the list of versions. Perhaps try in a clean virtual environment? Is this on Windows or some other platform?
