### ISSUE TITLE
not able to import GetMetaData

### ISSUE THREAD

**Issue by rvipandey** [facebookresearch/Kats#265]
Hi Everyone, 

I am not able to import  from kats.models.metalearner.get_metadata import GetMetaData, getting below error

ImportError: cannot import name '_mul_broadcast_shape' from 'gpytorch.utils.broadcasting' (/opt/conda/lib/python3.9/site-packages/gpytorch/utils/broadcasting.py)

Can anyone suggest me how to resolve this issue? I tried to optimize https://github.com/facebookresearch/Kats/blob/main/kats/models/metalearner/get_metadata.py file but getting same issue.

Regards,
Ravi

**Comment by yangbk560** [comment]
It seems pretty wired to me that IIRC, `GetMetaData` does not reply on gpytorch. @peiyizhang, any idea?

**Comment by yangbk560** [comment]
It will be great if you can share the snippet of the error message to help us debug. Thanks!

**Comment by rvipandey** [comment]
Hi @yangbk560 Thank you for your reply. After research i am able to solve this issue. issue with gpytorch but when i downloaded a stable version, the issue is resolved. 
pip install gpytorch==1.8.1
