### ISSUE TITLE
ERROR: No matching distribution found for gcc - please help

### ISSUE THREAD

**Issue by psxpa3** [facebookresearch/Kats#272]
Hi, I am working on an automation where KATS library is mentioned in the setup.py file with Python version 
```classifiers=[
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
```
The dockerfile installs Python 3.8 version as mentioned through this line
```VENV="source /app/py38-venv/bin/activate"```

The different packages being installed in the docker container is:
install_requires=[
        "gcc",
        "kats",
        "lighthouse-db",
        "mypy-extensions",
        "netcap-commons>=1.0.56",
        "pandas",
        "pmdarima",
        "pyro-ppl",
        "sklearn",
        "statsmodels",
        "torch",
    ],

On CI/CD pipeline, I am getting the following error for the docker container:

[91mERROR: Could not find a version that satisfies the requirement gcc (from netcap-forecastlib) (from versions: none)
[0m[91mERROR: No matching distribution found for gcc
[0mThe command '/bin/sh -c python3 -m pip install -e .' returned a non-zero code: 1

The full-stack for the error is as below:

Using cached https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/packages/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz (1.1 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Could not find a version that satisfies the requirement gcc (from netcap-forecastlib[dev]) (from versions: none)
ERROR: No matching distribution found for gcc
=================================== log end ====================================
ERROR: could not install deps [.[dev]]; v = InvocationError("/sparta/input/.tox/py36-test/bin/pip install --upgrade --trusted-host artifactory.oci.oraclecorp.com -i https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/simple '.[dev]'", 1)
___________________________________ summary ____________________________________
ERROR:   mypy: could not install deps [mypy, .[dev]]; v = InvocationError("/sparta/input/.tox/mypy/bin/pip install --upgrade --trusted-host artifactory.oci.oraclecorp.com -i https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/simple mypy '.[dev]'", 1)
ERROR:   lint: InvocationError for command /sparta/input/.tox/lint/bin/pip install --upgrade --trusted-host artifactory.oci.oraclecorp.com -i https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/simple --exists-action w .tox/.tmp/package/1/netcap-forecastlib-1.0.270.tar.gz (exited with code 1)
ERROR:   py36-test: could not install deps [.[dev]]; v = InvocationError("/sparta/input/.tox/py36-test/bin/pip install --upgrade --trusted-host artifactory.oci.oraclecorp.com -i https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/simple '.[dev]'", 1)

**Comment by peiyizhang** [comment]
Hi, thanks for asking and thanks for your interests in Kats. Were you trying to install gcc in virtualenv? Based on the following website, gcc cannot be installed in virtualenv. https://stackoverflow.com/questions/45267201/how-to-install-gcc-in-virtualenv
Hope it can solve your problem.

**Comment by psxpa3** [comment]
@peiyizhang  - thanks for the reply. However, my question is, the KATS installation is not compatible with the installed gcc version of my docker container. I have gcc version to be ```gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)```. Could you specify which gcc version can be used?

**Comment by michaelbrundage** [comment]
@psxpa3 per your logs above, this error is happening long before Kats. Sorry, but we can't help you debug your docker container/gcc setup.
