### ISSUE TITLE
MINIMAL_KATS = 1 is not working. Its trying to install all the dependencies from test_requirements.txt

### ISSUE THREAD

**Issue by nandi19k** [facebookresearch/Kats#278]
![image](https://user-images.githubusercontent.com/100563768/203714209-ee467767-9eb5-4c71-9359-1029960ea45a.png)

**Comment by marekb-sci** [comment]
this is the effect of neuralprophet in requirements.txt, where it probably shouldn't be. Also prophet appears in both requirements.txt and test_requirements.txt. These two dependecies in requirements.txt make MINIMAL_KATS option useless for now

**Comment by michaelbrundage** [comment]
Looks like this was broken in 484191df88db2f9f4e6b6cd1d4903f09015131f0
