### ISSUE TITLE
ImportError: cannot import name '_mul_broadcast_shape' from 'gpytorch.utils.broadcasting' (/usr/local/lib/python3.8/dist-packages/gpytorch/utils/broadcasting.py)

### ISSUE THREAD

**Issue by abcd-arl** [facebookresearch/Kats#289]
This happens when running `from kats.models.metalearner.get_metadata import GetMetaData` from Google Colab.

**Comment by awecx** [comment]
Downgrading gpytorch to 1.8.0 solved the issue for me.

**Comment by JeremyWhittaker** [comment]
> 

Thanks!
