### ISSUE TITLE
kats installation error

### ISSUE THREAD

**Issue by aayushL** [facebookresearch/Kats#325]
Hello,
I am trying to install kats library using pip but I am getting below error:
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error

        python setup.py clean did not run successfully.
        exit code: 1

        [10 lines of output]
        Running from numpy source directory.

        `setup.py clean` is not supported, use one of the following instead:

          - `git clean -xdf` (cleans all files)
          - `git clean -Xdf` (cleans all versioned files, doesn't touch
                              files that aren't checked into the git repo)

        Add `--force` to your command to use it anyway if you must (unsupported).

        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by shreyastalamakki** [comment]
same issue: 
![image](https://github.com/facebookresearch/Kats/assets/41263573/effc8df6-2421-4b10-a889-a122f179fe26)

**Comment by shreyastalamakki** [comment]
@iamxiaodong is there any update on this?

**Comment by sankexin** [comment]
> Hello, I am trying to install kats library using pip but I am getting below error: [end of output]
> 
> ```
>     note: This error originates from a subprocess, and is likely not a problem with pip.
>     ERROR: Failed building wheel for numpy
>     Running setup.py clean for numpy
>     error: subprocess-exited-with-error
> 
>     python setup.py clean did not run successfully.
>     exit code: 1
> 
>     [10 lines of output]
>     Running from numpy source directory.
> 
>     `setup.py clean` is not supported, use one of the following instead:
> 
>       - `git clean -xdf` (cleans all files)
>       - `git clean -Xdf` (cleans all versioned files, doesn't touch
>                           files that aren't checked into the git repo)
> 
>     Add `--force` to your command to use it anyway if you must (unsupported).
> 
>     [end of output]
> 
>     note: This error originates from a subprocess, and is likely not a problem with pip.
>     ERROR: Failed cleaning build dir for numpy
>   Failed to build numpy
>   ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

#python3.8
pip install numpy
pip install pandas
pip install convertdate
pip install lunarcalendar
pip install holidays==0.23
pip install tqdm
pip install pystan==2.19.1.1
pip install fbprophet==0.7.1
pip install kats
pip install Packaging==21.3

**Comment by sankexin** [comment]
#python3.8
pip install numpy
pip install pandas
pip install convertdate
pip install lunarcalendar
pip install holidays==0.23
pip install tqdm
pip install pystan==2.19.1.1
pip install fbprophet==0.7.1
pip install kats
pip install Packaging==21.3

**Comment by Nutingnon** [comment]
I met the same error. Kats is so difficult to install. and it seems the authors won't do any updates

**Comment by sankexin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Shuimo03** [comment]
if python version is 3.7 the solution solved, this is my docker build result:
![image](https://github.com/facebookresearch/Kats/assets/22347407/ad4fa990-7af5-4eea-93cf-9ea4e5e54f19)

**Comment by Shuimo03** [comment]
this is example:
```python
import numpy as np
import pandas as pd

from kats.consts import TimeSeriesData
from kats.detectors.cusum_detection import CUSUMDetector

# simulate time series with increase
np.random.seed(10)
df_increase = pd.DataFrame(
    {
        'time': pd.date_range('2019-01-01', '2019-03-01'),
        'increase':np.concatenate([np.random.normal(1,0.2,30), np.random.normal(2,0.2,30)]),
    }
)

# convert to TimeSeriesData object
timeseries = TimeSeriesData(df_increase)

# run detector and find change points
change_points = CUSUMDetector(timeseries).detector()


print("change_points:",change_points)
```

![image](https://github.com/facebookresearch/Kats/assets/22347407/a065e0a3-d9b3-44b1-8797-e232550f187d)

**Comment by sankexin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by FortuneStar** [comment]
You can refer to [here](https://blog.csdn.net/FortuneLegend/article/details/132694576)

**Comment by swimmingCreative** [comment]
> if python version is 3.7 the solution solved, this is my docker build result: ![image](https://user-images.githubusercontent.com/22347407/267918972-ad4fa990-7af5-4eea-93cf-9ea4e5e54f19.png)

can you share your requirements? Thanks in advance.

**Comment by Shuimo03** [comment]
> > if python version is 3.7 the solution solved, this is my docker build result: ![image](https://user-images.githubusercontent.com/22347407/267918972-ad4fa990-7af5-4eea-93cf-9ea4e5e54f19.png)
> 
> can you share your requirements.txt? Thanks in advance.

sorry, this is too long ago
