### ISSUE TITLE
Add STUMPY Matrix Profile Analysis

### ISSUE THREAD

**Issue by seanlaw** [facebookresearch/Kats#47]
Thank you for putting together this really awesome time series analysis package. Given that the aim of Kats is to provide a one-stop-shop for time series analysis, I was wondering if there are any plans/interest to incorporate time series analyses with matrix profiles using the [STUMPY](https://github.com/TDAmeritrade/stumpy) package. Given that STUMPY only depends on NumPy, SciPy, and Numba (all of which are Kats dependencies) and it is has 100% code coverage, it may be a great complement to the Kats ecosystem.

Full disclosure, I am the creator and core maintainer of the STUMPY package. Thank you for your consideration!

**Comment by iamxiaodong** [comment]
Hi @seanlaw, thanks for this suggestions! Just want to give you a heads up that our team is looking into this, we will provide more feedback to this issue once we figure this out!

**Comment by seanlaw** [comment]
Please let me know if there is anything I can do to help

**Comment by seanlaw** [comment]
👋 @iamxiaodong I wanted to follow up on this to see if there is any interest. Otherwise, we can close this issue and reassess in the future.
