### ISSUE TITLE
Kats website sharing Google analytics ID with hydra.cc

### ISSUE THREAD

**Issue by omry** [facebookresearch/Kats#48]
Kats website sharing Google analytics ID with hydra.cc (UA-149862507-1).
From the source of https://facebookresearch.github.io/Kats/:
![image](https://user-images.githubusercontent.com/376455/122881400-f9821280-d2ef-11eb-98be-4316d1dd60b1.png)

Please use your own Google analytics ID, you are messing up the analytics of hydra.cc.

Thanks.

**Comment by Ahmetburhan** [comment]
Hi Omry
I have resolved the issue please check and close the task,
Sorry for the in convenience

https://github.com/facebookresearch/Kats/commit/dc540df137adfb6300ad644ae5b9a2b678058f6b

Thank you

**Comment by michaelbrundage** [comment]
Also removed from API pages.

**Comment by omry** [comment]
Thanks. Curious how that happened? did you use the Hydra website as a base?

It will probably be a few days before I am sure there are no more additional hits coming from the Kats website.

**Comment by omry** [comment]
Looking clean now, thanks for fixing it.
