### ISSUE TITLE
Feature Request: Kalman Filter and Related Variants

### ISSUE THREAD

**Issue by brotherdust** [facebookresearch/Kats#50]
May I suggest adding Kalman filter? Seems like it would be a good fit!

**Comment by iamxiaodong** [comment]
Hi @brotherdust, thanks for this suggestion! We're open if the open source community would like to implement Kalman filter model, as well as other forecasting or detection models to Kats. Please submit a PR if you're interested!

**Comment by michaelbrundage** [comment]
Resolving due to inactivity.
