### ISSUE TITLE
Other Software

### ISSUE THREAD

**Issue by firmai** [facebookresearch/Kats#51]
I know it is early days, but the package seems to borrow from other solutions already out there, maybe some level of attributions would be good.

**Comment by iamxiaodong** [comment]
Hi @firmai: thanks for creating this issue! Kats is depended on several other packages especially statsmodels, pandas, numpy, pytorch, prophet, etc. (listed in our requirements.txt as well), so we highlighted those in our inline documentations. Please let us know if we missed anything, and what are the specific attributions you refer to. Thanks!
