### ISSUE TITLE
Feature request: __getitem__ returning univariate TimeSeriesData

### ISSUE THREAD

**Issue by Galsor** [facebookresearch/Kats#57]
Hello,
First of all thanks for this amazing work! It's the lib I was looking for for so long.
Manipulating multivariate time series can still be quite frustrating.
Have you plan to add __getitem__ method to TimeSeriesData object to enable pandas-like column access `df["column_name"]
` ?
It could be especially convenient to get a univariate TimeSeriesData object ready to be used in Kats models.

Meanwhile any workaround more convinient than the following would be welcome:
```python
uni_ts = TimeSeriesData(multi_ts.value["col_name"])
```

Best regards,

**Comment by michaelbrundage** [comment]
Thanks, Galsor, it's a good idea. We do have `TimeSeriesData.__get_item__`, but could overload it as pandas does. PRs always welcome, otherwise we can get to it eventually.

**Comment by jeffhandl** [comment]
Thanks @Galsor, I am landing the fix for this now.

**Comment by jeffhandl** [comment]
Issue is resolved.  Note that this fix only allows you to reference the columns with string names.
