### ISSUE TITLE
Hyperparmeter tuning is not working

### ISSUE THREAD

**Issue by Fayepasvouri** [facebookresearch/Kats#58]
Hi, 

I am following the steps as requested. I can build models like arima, holter, prophet but I cannot do hyper parameter tuning. I receive error: No frequency information was provided with date index and no frequency could be inferred. Then, I set freq='MS' but I still receive the same error. Any clue?

Thanks,
faye

**Comment by iamxiaodong** [comment]
Hi @Fayepasvouri, sorry to hear that you cannot use HPT, do you mind sharing your code example and errors? Thanks.

**Comment by MoKazemi9** [comment]
@Fayepasvouri , do you still have issue with hyper parameter tuning? if, not we can close this issue. Thanks

**Comment by michaelbrundage** [comment]
Resolving due to inactivity.
