### ISSUE TITLE
Minor style problem in homepage (gh-page)

### ISSUE THREAD

**Issue by ilmalte** [facebookresearch/Kats#59]
Hi there!

I was wondering to contribute and fix a minor style problem in homepage.

The index has a main section tag with a "features_3azU" class. This section has 2 rows: 
- the first one is a generic description of the package;
- the second one contains all the 4 features divided by a `col col--3` class.

For the styling I think could be better to put the description paragraph inside a `col col--12` class. 
In this way this section will have a 16px right and left padding and will be better aligned to the features in the following row.

**Comment by iamxiaodong** [comment]
Hi @ilmalte, thanks for your interests to fix this, please feel free to submit a PR so that our team can review the changes.

**Comment by michaelbrundage** [comment]
Resolving due to inactivity.
