### ISSUE TITLE
Use running index as time_col

### ISSUE THREAD

**Issue by orko19** [facebookresearch/Kats#67]
I have time series data with the `time_col` is the index of the dataframe:
```
df = [index  value 
            0         31
            1          22
            2         15
            3         77]
```
When I am trying to convert it to `TimeSeriesData`, the index is automatically transform to epoch time. `(e.g. 1970-01-01 00:00:00.000000095)`
Is there a way to keep the time_col as the mere index when using `TimeSeriesData`

**Comment by jeffhandl** [comment]
You need to specify the name of the time column if it is not `time`.  You can do `TimeSeriesData(df, time_col_name='index')`.

**Comment by orko19** [comment]
I am doing just that:

df :
```

0,0.09177
1,0.09567
2,0.08444
3,0.08971


```
And then I run:
`TimeSeriesData(df, time_col_name='index')
`But then the index is automatically transformed to datetime:
```
                            index         0
0   1970-01-01 00:00:00.000000000  0.091773
1   1970-01-01 00:00:00.000000001  0.095667
2   1970-01-01 00:00:00.000000002  0.084443
3   1970-01-01 00:00:00.000000003  0.089711
```

**Comment by jeffhandl** [comment]
Yes, the times need to be Datetimes.

**Comment by orko19** [comment]
@jeffhandl OK , but let's say I want to treat them just as order and not specifically datetime - is it possible?

**Comment by jeffhandl** [comment]
No, you need datetime values in the time column - that is required.

**Comment by orko19** [comment]
@jeffhandi will be it presented in the future or there is a workaround? since ordered data is actually can be treated as a time series, even if the index is not specifically datetime

**Comment by jeffhandl** [comment]
@orko19 If you have `ts_df = TimeSeriesData(df, time_col_name='index')`, you can recover the indices by doing `ts_df.time.index`.  Does that help?

**Comment by orko19** [comment]
@jeffhandl When I run on my dataframe:
```
df.apply(lambda x : CUSUMDetector(TimeSeriesData(pd.DataFrame(x['value']).
                                                                   reset_index(), time_col_name="index")).
                            detector(), axis=1)
```
I get:
```
[(TimeSeriesChangePoint(start_time: 1970-01-01 00:00:00.000000095, end_time: 1970-01-01 00:00:00.000000095, confidence: 1.0), <kats.detectors.cusum_detection.CUSUMMetadata object at 0x1db27ef40>)]
[(TimeSeriesChangePoint(start_time: 1970-01-01 00:00:00.000000057, end_time: 1970-01-01 00:00:00.000000057, confidence: 1.0), <kats.detectors.cusum_detection.CUSUMMetadata object at 0x1db27e9a0>)]
[(TimeSeriesChangePoint(start_time: 1970-01-01 00:00:00.000000229, end_time: 1970-01-01 00:00:00.000000229, confidence: 1.0), <kats.detectors.cusum_detection.CUSUMMetadata object at 0x1db27e6d0>)]
[(TimeSeriesChangePoint(start_time: 1970-01-01 00:00:00.000000095, end_time: 1970-01-01 00:00:00.000000095, confidence: 1.0), <kats.detectors.cusum_detection.CUSUMMetadata object at 0x1db27ef10>)]
[(TimeSeriesChangePoint(start_time: 1970-01-01 00:00:00.000000057, end_time: 1970-01-01 00:00:00.000000057, confidence: 1.0), <kats.detectors.cusum_detection.CUSUMMetadata object at 0x1db27e340>)]
```
So I meant to ask if there is a way that the output of the detector will be the actual index? Or a workaround to go back from TimeSeriesChangePoint to row/index in the original dataframe?

**Comment by jeffhandl** [comment]
Yes, let's say `ts_df` is the name o the time series and `cp` is the name of a changepoint.  Then `cp[0][0].start_time` is the time of the changepoint, so you can do `ts_df.time_to_index().get_loc(cp[0][0].start_time)`.
