### ISSUE TITLE
Model updates

### ISSUE THREAD

**Issue by pablojadz** [facebookresearch/Kats#69]
Hi all,

thanks for a great package. Sorry to ask a question here (not necessarily and issue yet)  but can't find the users group 

I have a quick question, is it possible to update a Prophet model as new data arrives or is retraining from scratch the only alternative?

Say you have a df like this
```
from kats.models.prophet import ProphetModel, ProphetParams
from kats.consts import TimeSeriesData
import pandas as pd
import numpy as np

df = pd.DataFrame({"time": pd.date_range('2020-01-01', '2020-01-21'), "value": np.random.randn(21)})
ts = TimeSeriesData(df)

model = ProphetModel(ts, ProphetParams())
model.fit()
```

and latter on we add another datapoint to df as in 

```
df = df.append({"time": pd.to_datetime('2020-01-22'), "value": 0}, ignore_index=True)
```

I'm assuming that it would be possible and efficient to just update the `model`

Thanks for reading

**Comment by michaelbrundage** [comment]
Hi @pablojadz, sorry for the much-delayed response. Prophet doesn't support incremental training. See https://github.com/facebook/prophet/issues/1565
