### ISSUE TITLE
How to add exogenous regressors to kats.models.sarima.SARIMAModel ?

### ISSUE THREAD

**Issue by satya-pattnaik** [facebookresearch/Kats#70]
Using the keyword `exog` for kats' SARIMA module throws an error. <br>
Is the kats SARIMA suited for modelling exogenity?

I am pasting a snip:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/22102468/123926235-5002e700-d9a9-11eb-98c0-497708300a99.png)

If there is a way to pass ```exog regressors```, it will be really helpful to show an example snippet.

**Comment by Axemen** [comment]
Hey @satya-pattnaik, I did some digging and found out that the model is properly passing the exogenous variable to the predict function. So for the moment this won't work. 

I have created a PR that fixes this issue and adds a test to ensure that it works in the future. #75

**Comment by jeffhandl** [comment]
This issue has been resolved with PR #75
