### ISSUE TITLE
unable to build wheel for fbprophet while trying to install Kats in Win 10

### ISSUE THREAD

**Issue by kunalrayind** [facebookresearch/Kats#71]
1. My environment is Win 10, with conda 4.9.2 and Python 3.7.6
2. While trying to install Kats (pip install kats), I am getting the error: Building wheel for fbprophet (setup.py) ... error
3. More lines from the error message are in attached file
[Kats_error.txt](https://github.com/facebookresearch/Kats/files/6740490/Kats_error.txt)
4. I had an older working fbprophet, faced same errors in trying to upgrade (pip install --upgrade fbprophet).
5. Anybody know how to fix this?

**Comment by sathish331977** [comment]
fails with ERROR: Failed building wheel for fbprophet on ubuntu (20.04)

**Comment by MoKazemi9** [comment]
Hi @kunalrayind @sathish331977 , thank you for the issue, please see: 
https://github.com/facebookresearch/Kats/issues/49

**Comment by kunalrayind** [comment]
Thanks MoKazemi9, but following the suggested steps did not solve my problem.
It seems the problem is not with pystan or gcc.
Please note that fbprophet installed successfully (version 0.7.1)
I am putting the error lines below:
      File "D:\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
             if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
      File "D:\Anaconda3\lib\genericpath.py", line 30, in isfile
             st = os.stat(path)
       TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
       ----------------------------------------
        ERROR: Failed building wheel for fbprophet
        Running setup.py clean for fbprophet
        Failed to build fbprophet

**Comment by yqstar** [comment]
fails with ERROR: Failed building wheel for fbprophet on macos

**Comment by sunmichace** [comment]
fails with ERROR: Failed building wheel for fbprophet on macos

**Comment by sunmichace** [comment]
same error 
env:
macos m1
python3.8

**Comment by stonebb** [comment]
win10，python 3.8.10 . conda

pytho3.6 不OK，因为会有from __future__ import annotations，，，
所以做了新镜像 conda create --name kats python=3.8
如果直接安装kats会有问题：
其中主要为ERROR: Failed building wheel for fbprophet


因此先进行fbprophet安装，其中需要首先按照pystan，采用conda  安装
python -m pip install -U pip
 conda install -c conda-forge pystan
pip install fbprophet

安装完成done，但是依赖库中文件有缺失，然后将github上kats文件中源代码放入所在依赖库

**Comment by GXY2017** [comment]
win10, python3.8.3, conda
````
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
````

**Comment by michaelbrundage** [comment]
Kats is now on 0.2.0. Resolving old 0.1.0 installation issues.

**Comment by yqstar** [comment]
您的邮件已收到，我会第一时间给予回复的。合肥工业大学 邢勇强
