### ISSUE TITLE
How Kats is differ from Sktime?

### ISSUE THREAD

**Issue by elisim** [facebookresearch/Kats#78]
Hi FB team,

Thank you for open-sourcing your great package.
I would like to know what is the difference between Kats and Sktime:

[Sktime](https://www.sktime.org/en/latest/) - A unified framework for machine learning with time series

Which features Kats offers, which are not included in Sktime?

Thank you,
Eli

**Comment by iamxiaodong** [comment]
Thanks for the question, @elisim! After a quick review, sktime is a great Python package for time series analysis, and I believe the main differences are:
1. **Detection algorithms**. Kats provides a set of detection algorithms to detect various patterns from given time series, such as outlier, change point, slow trend change, seasonalities, etc., I didn't see any relevant offerings from sktime.
2. **More advanced forecasting techniques**. Both Kats an sktime provides fundamental forecasting models and techniques such as ensemble, various statistical models, etc., However, Kats has more powerful and recent techniques such as meta-learning and nowcasting, which are powerful tools for many industry scenarios.
3. **Feature extraction**. Both Kats and sktime provide hand-crafted statistics as time series features, being used for regression or classification, we're also working on more advanced embedding techniques for our next release.
4. sktime provides better APIs for classification and regression, where Kats does not provide any tools for that.

Hopefully we can discuss more details with the sktime team and see what is the best way to provide a better time series analysis framework to the open source community :)
