### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by candalfigomoro** [facebookresearch/Kats#81]
It would be nice to add a Kats package to conda-forge https://conda-forge.org (prophet is already available in conda-forge: https://github.com/conda-forge/prophet-feedstock).

The "prophet" conda package should probably be used as dependency (instead of the "fbprophet" package), also see https://github.com/facebookresearch/Kats/issues/62

**Comment by rpanai** [comment]
I believe this can be closed [https://github.com/conda-forge/kats-feedstock](https://github.com/conda-forge/kats-feedstock)

I updated the README.md accordingly in this [PR](https://github.com/facebookresearch/Kats/pull/253).
