### ISSUE TITLE
Add strategies for positive predictions (e.g. ProphetPos support)

### ISSUE THREAD

**Issue by candalfigomoro** [facebookresearch/Kats#82]
In order to force predictions to be positive (this is a common requirement for many business-related time series), the prophet package can be used with the ProphetPos class (see "**Approach 5**" here: https://github.com/facebook/prophet/issues/1668#issue-701631525).

It would be nice to add a "ProphetPosModel" to Kats, so we can force predictions to be positive when we use prophet in Kats.

Maybe a positive constraint could also be added to the other models supported by Kats (SARIMA etc.).

**Comment by yangbk560** [comment]
Thanks for the suggestion and we will keep this in mind for new feature development! Meanwhile, would it make sense to transform the data first (e.g., y' = log(ts)) and build model based on y' then transform it back. In this we can solve the problem of negative forecasts.
