### ISSUE TITLE
does Kats support Multivariate time series forecasting?

### ISSUE THREAD

**Issue by shrikantpandey13** [facebookresearch/Kats#83]
Hi,

I want to know that does Kats supports Multivariate time series forecasting? Please let me know

Thank you very much :)

**Comment by Axemen** [comment]
Hey @shrikantpandey13 ,

Kats does support Multivariate forecasting for some of its models but not all. 

Here is a link to the tutorial notebook in this repo that contains an example of using kats with such a timeseries 

https://github.com/facebookresearch/Kats/blob/master/tutorials/kats_201_forecasting.ipynb

**Comment by shrikantpandey13** [comment]
Query is solved.
