### ISSUE TITLE
CI fails missing requirement

### ISSUE THREAD

**Issue by omrihaber** [facebookresearch/Kats#85]
I saw the CI failing because of a library called deprecated which is missing from the requirements.txt

Made a [PR](https://github.com/facebookresearch/Kats/pull/84) that adds the requirement.

Should these requirements be separate from the requirements.txt and create a test_requirements.txt or all of the dependencies for testing and development are stated at requirements.txt?

**Comment by michaelbrundage** [comment]
Good catch, thanks -- that was my error. I thought I had added it to `requirements.txt`, but apparently not. For now, we don't have separate requirements and test requirements, and for this instance it belongs in `requirements.txt` regardless. Thanks for the PR!
