### ISSUE TITLE
What's the difference between TSfeatures and tsfeatures package?

### ISSUE THREAD

**Issue by pawarbi** [facebookresearch/Kats#88]
Hi, 

Is the TSfeatures available in Kats same as the tsfeatures package (https://pypi.org/project/tsfeatures/) ? Have you done any benchmarking against that package or the original tsfeatures in R?

For example, the link above also shows "Comparison with the R implementation (sum of absolute differences)". It would be great to have a similar comparison on M3/M4 data. 

Thanks,

**Comment by iamxiaodong** [comment]
Thanks for the question, @pawarbi! I can provide a little bit context on this
1. Kats tsfeatures module provides 68 features while the tsfeatures Python package you shared has 22 features, so this differs a lot in terms of the numbers; also, when we started to develop this module (internally at facebook), there is no good feature extraction libraries in Python back then. Also, we're currently developing a neural network based approach for much faster and informative time series embeddings which we hope to release in our next release cycle.
2. The R version is definitely great, and we also have contributors from the authors of the original paper and package so we're fully aware of the development.
3. For performance comparison, we haven't dive into details but you're more than welcome to try our version on M3/M4 dataset and report back to the open source community, our team can also review the results afterwards!

**Comment by iamxiaodong** [comment]
I'll close this issue since the question is resolved.
