### ISSUE TITLE
Error while importing CUSUMDetectorTest in tutorial tkats_202_detection.ipynb

### ISSUE THREAD

**Issue by loicduffar** [facebookresearch/Kats#90]
I get the error below while importing CUSUMDetectorTest in Tutorial "Daily Seasonality with Interest Windows" (tkats_202_detection.ipynb)

I solved the issue by copying the CSV file in the subfolder kats/kats/data of my running notebook folder

It looks like a bug in test_detectors.py?
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-6570ee1979fa> in <module>
----> 1 from kats.tests.test_detectors import CUSUMDetectorTest
      2 
      3 # Here's where we load the seasonal data
      4 np.random.seed(1)
      5 periodicity=24

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kats\tests\test_detectors.py in <module>
    105     multi_data_path = "kats/kats/data/multivariate_anomaly_simulated_data.csv"
    106 
--> 107 data = pd.read_csv(data_path)
    108 data.columns = ["time", "y"]
    109 ts_data = TimeSeriesData(data)
.
.
.
FileNotFoundError: [Errno 2] No such file or directory: 'kats/kats/data/air_passengers.csv'

```

**Comment by iamxiaodong** [comment]
Hi @loicduffar, is there a specific reason that you want to run this test? it serves as unit tests and works well for our testing environment on Github Actions; yes you need to download this data set to your local directory to be accessible, in the future we will provide `load_data` functionalities which will make the process much easier.

**Comment by loicduffar** [comment]
Hi @ iamxiaodong,
If you are aware of the problem, that's OK for me, because I found the solution

**Comment by jeffhandl** [comment]
Thanks for pointing this out @loicduffar!  I will be landing a change to `test_detectors.py` that should fix this.

**Comment by jeffhandl** [comment]
It should be resolved now.
