### ISSUE TITLE
MKDetector works only for daily data - Support of montlhy data would be great

### ISSUE THREAD

**Issue by loicduffar** [facebookresearch/Kats#93]
I have tried running MKDectector on monthly values, but the algorithm is obviously limited to daily data although this limitation is not mentioned (for instance, CUSUM works on monthly data).

What a pity not to be able to process the monthly data. I would like you to add this functionality, in particular concerning the treatment of hydroclimatic data for the challenges of climate change.

Thank you for sharing this great tool

**Comment by jeffhandl** [comment]
@loicduffar Can you share an example that you are trying to use for the `MKDetector`?

**Comment by loicduffar** [comment]
@jeffhandl 
Here is a csv file with Monthly Air temperature evolution of my city in FRANCE
(extract frome [kaggle](https://www.kaggle.com/berkeleyearth/climate-change-earth-surface-temperature-data?select=GlobalLandTemperaturesByCity.csv)

**Comment by jeffhandl** [comment]
@loicduffar Thanks for sharing this data set.  I don't see any reason why you can't run `MKDectector` with a data set like this one.  Can you tell me what is going wrong for you?
